### ISSUE TITLE
Too aggressive?

### ISSUE THREAD

**Issue by rosskarchner** [cobrateam/django-htmlmin#108]
This seems sort of wrong to me (using the latest release):

```
>>> str= "<b>hey </b>you"                                                                                                      
>>> html_minify(str)
u'<html><head></head><body><b>hey</b>you</body></html>'
>>> 
```

which would render like "**hey**you", when the intent would pretty clearly be "**hey** you"

**Comment by andrewsmedina** [comment]
Hi @rosskarchner it's looks like a bug. The minify should not remove the space inside <b> tag.

**Comment by Ryuno-Ki** [comment]
Affects us, too. Even with v0.10.0.

@andrewsmedina Can you at least point to the line in source code where the minification happens?
Workaround using `EXCLUDE_FROM_MINIFYING` is too fragile with Django's URL routing IMHO …

**Comment by Ryuno-Ki** [comment]
Using [undocumented `EXCLUDE_TAGS_FROM_MINIFYING`](https://github.com/cobrateam/django-htmlmin/blob/814ced5c22592563d534927c4cc78542bf53a2e2/htmlmin/minify.py#L21) is usable as workaround.

**Comment by andrewsmedina** [comment]
We should document `EXCLUDE_TAGS_FROM_MINIFYING` setting

**Comment by rosskarchner** [comment]
so , `EXCLUDE_TAGS_FROM_MINIFYING` would solve my example above, if I add 'b' to that list?

**Comment by Ryuno-Ki** [comment]
What does your python shell tell you? :-)
