### ISSUE TITLE
error with gzip on nginx

### ISSUE THREAD

**Issue by narnikgamarnikus** [cobrateam/django-htmlmin#114]
If I try add `gzip on` in nginx.conf, PageSpeed Insights return 

> The server closed the connection before sending a full response. Ensure that the page loads in a browser and try again

**Comment by andrewsmedina** [comment]
We need to know why this happen

**Comment by narnikgamarnikus** [comment]
This happens when the gzip is enabled in nginx.conf

**Comment by andrewsmedina** [comment]
what version of Django are you using?

**Comment by narnikgamarnikus** [comment]
I use htmlmin in two django projects with versions 1.10 and 1.11.1

**Comment by mkhndrsn** [comment]
Hi we had this same issue on 1.11. Was this ever resolved?

**Comment by andrewsmedina** [comment]
The support for django 1.11+ that fixes this bug was released in htmlmin 0.11
