### ISSUE TITLE
Getting net::ERR_INCOMPLETE_CHUNKED_ENCODING with Chrome

### ISSUE THREAD

**Issue by night-crawler** [cobrateam/django-htmlmin#115]
Hi!

After updating to `Django==1.11.1` and `django-htmlmin==0.10.0` got this error. Cannot reproduce with FF. Disabling htmlmin fixes the problem. Tried to rewrap TemplateResponse with HttpResponse in `HtmlMinifyMiddleware.process_response()` without any effect. Cannot find anything with debugger. Anyone knows what's this?

Thanks!

**Comment by antiline** [comment]
Yes. I have already same issue on same setting.

**Comment by bartmika** [comment]
Me too. +1

**Comment by dieudv** [comment]
Me too :+1:

**Comment by andrewsmedina** [comment]
The support for django 1.11+ that fixes this bug was released in htmlmin 0.11
