### ISSUE TITLE
Not working with django 2.1 

### ISSUE THREAD

**Issue by benoitmaudet** [cobrateam/django-htmlmin#127]
The module is not working with django 2.1 and python 3.5.3.

Html code is printed as byte : «b'<!doctype html>\n'...»

**Comment by saeedsq** [comment]
HTML minify is not working with Django 2.1 and python 3.6
Causing below error in nginx:

[error] 21883#21883: *22 upstream prematurely closed connection while reading upstream, 

Without any error in gunicorn or django log files

**Comment by andrewsmedina** [comment]
The support for 2.1 was released in the htmlmin 0.11 version
