### ISSUE TITLE
travis-ci.org shutdown

### ISSUE THREAD

**Issue by tisdall** [cobrateam/django-htmlmin#149]
travis-ci.org was scheduled for shutdown Dec 31, 2020 .  It seems to slowly still be working at the moment, but apparently people are intended to transition over to travis-ci.com or use something else.

https://github.com/Pylons/deform is another open source project that switched from Travis over to Github Actions for automated testing, so it may be a good template to mimic for switching.

**Comment by andrewsmedina** [comment]
I'm +1 to move to github actions

**Comment by fsouza** [comment]
@andrewsmedina I can take care of that if you want or if you're not already working on it.
