### ISSUE TITLE
&lt; and &gt; get converted to < and > respectively

### ISSUE THREAD

**Issue by MTecknology** [cobrateam/django-htmlmin#55]
I have this snippet of an html page::

    <div class="highlight"><pre><span class="cp">&lt;!DOCTYPE html&gt;</span>
    <span class="nt">&lt;html</span> <span class="na">lang=</span><span class="s">&quot;en&quot;</span> <span class="na">dir=</span><span class="s">&quot;ltr&quot;</span><span class="nt">&gt;</span>
        <span class="nt">&lt;head&gt;</span>
            <span class="nt">&lt;title&gt;</span>My Site!<span class="nt">&lt;/title&gt;</span>
        <span class="nt">&lt;/head&gt;</span>
        <span class="nt">&lt;body&gt;</span>
            <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">&quot;pagebody&quot;</span><span class="nt">&gt;</span>
                %include
            <span class="nt">&lt;/div&gt;</span>
        <span class="nt">&lt;/body&gt;</span>
    <span class="nt">&lt;/html&gt;</span>
    </pre></div>

When I try to run this through html_minify() I will wind up with the &lt; and &gt; pieces of text being treated as html tags. I think the problem with that is rather obvious, but if I didn't make sense, let me know and I'll try to explain better.

**Comment by alessio** [comment]
I've stumbled upon this today:
```
TemplateSyntaxError at /home/
Could not parse the remainder: '&gt;' from '&gt;'
```

The affected snippet follow:
```
<html lang="en"><head></head><body class="main on-{{ NAME }}">{% if page_obj and page_obj.number &gt; 1 %} 
```

**Comment by MTecknology** [comment]
Alrighty, the one issue reported has been resolved and this is something I've since written my own custom implementation of. In order to prevent this issue from becoming a collection bucket, I'm closing it.
