### ISSUE TITLE
Why response.status_code == 200 only

### ISSUE THREAD

**Issue by Alcolo47** [cobrateam/django-htmlmin#97]
There is reason to limit the html_minify process to page with "OK"  status ?
Why not Error 404 or any what else ?

**Comment by dbykadorov** [comment]
+1
My error pages also not minified (and html/css markup fails). Can this be fixed?

**Comment by andrewsmedina** [comment]
we can minify all responses with 'text/html'

**Comment by dbykadorov** [comment]
Thanks!
